kotlin.code.style=official

#Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=false
org.gradle.daemon=false
org.gradle.configureondemand=false
org.gradle.configuration-cache=false

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false
#MPP
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true

#Development
development=true

# Disabled due to https://youtrack.jetbrains.com/issue/KT-65761
kotlin.native.disableCompilerDaemon = true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
